### ISSUE TITLE
File not found error ~partytown/debug/partytown-sw.js

### ISSUE THREAD

**Issue by haunguyenlxag** [netlify/hydrogen-netlify-starter#40]
To Reproduce
Python version set to 2.7
Now using node v16.19.0 (npm v8.19.3)
Using ruby version 2.7.2
Using PHP version 8.0

Steps to reproduce the behaviour below:

We are using the default package: https://github.com/netlify/hydrogen-netlify-starter
Intergrate with partytown https://partytown.builder.io/shopify-hydrogen
1. After pushing the code to github.
2. We use netlify to deploy.
3. After deploy success. Don't any error in deploy log
Check site https://netlify.bluecomvn.com. An error appeared under console.log.
When we visit the website. An error appeared on console.log.
We're not sure if it's located in dist/client/ ~partytown/debug/partytown-sw.js
File not found error ~partytown/debug/partytown-sw.js

Note: We have test under local working fine
![2023-01-05_13-25](https://user-images.githubusercontent.com/107162110/210715445-1b703b7f-13b6-4f06-bf86-77b176aa3ad3.png)

**Comment by ericapisani** [comment]
Hi @haunguyenlxag ,

Thanks for reaching out. I've noticed that you've also submitted a ticket with our support team, so in order to centralize all communications any updates on this will be provided through that other ticket.

In the meantime I'll leave this issue open until we've had a chance to investigate this.

**Comment by sarahetter** [comment]
Issue is fixed in version 1.1.4
